<template>
    <div>
      <!-- Navigation bar -->
      <div class="navbar">
        <router-link to="/">Home</router-link>
        <router-link to="/q1">Go to Q1</router-link>
        <router-link to="/q2">Go to Q2</router-link>
        <router-link to="/q3">Go to Q3</router-link>
        <router-link to="/q4">Go to Q4</router-link>
        <router-link to="/q5">Go to Q5</router-link>
        <router-link to="/q6">Go to Q6</router-link>
        <router-link to="/q7">Go to Q7</router-link>
        <router-link to="/q8">Go to Q8</router-link>
        <router-link to="/q9">Go to Q9</router-link>
        <router-link to="/q10">Go to Q10</router-link>
        <router-link to="/q11">Go to Q11</router-link>
        
      </div>
  
      <h2>a. Text Interpolation</h2>
      <p>Text interpolation allows you to insert dynamic values into HTML text by enclosing them in curly braces ({{ }}). For example, you can use it to display the value of a variable or the result of a JavaScript expression.</p>
  
      <h2>b. Raw HTML [v-html]</h2>
      <p>Raw HTML allows you to insert raw HTML into your templates using the v-html directive. This is useful for cases where you need to render HTML that is generated by a server or another third-party library.</p>
  
      <h2>c. Attribute Bindings [v-bind:id]</h2>
      <p>Attribute bindings allow you to bind dynamic values to HTML attributes using the v-bind directive. This allows you to dynamically change the behavior of HTML elements based on the state of your application.</p>
  
      <h2>d. JavaScript expressions inside syntax i.e. {{ }}</h2>
      <p>JavaScript expressions allow you to use JavaScript expressions inside your templates by enclosing them in curly braces ({{ }}). This allows you to perform calculations, manipulate data, and control the flow of your application from within your templates.</p>
  
      <div id="app">
        {{ message }} <!-- Text Interpolation -->
  
        <div v-html="rawHTML"></div> <!-- Raw HTML [v-html] -->
  
        <button v-bind:id="elementId">Button</button> <!-- Attribute Bindings [v-bind:id] -->
  
        {{ num1 + num2 }} <!-- JavaScript expressions inside syntax -->
      </div>
    </div>
  </template>
  
  <script>
  export default {
    data() {
      return {
        message: 'Hello, Vue3!',
        rawHTML: '<strong>Strong text demo</strong>',
        elementId: 'bound-id',
        num1: 20,
        num2: 22,
      };
    },
  };
  </script>
  
  <style scoped>

body {
  position: relative;
  background-color: #f0f0f0; /* Light gray background */
  font-family: 'Arial', sans-serif;
  margin: 0;
  padding: 0;
  overflow-x: hidden;
}

.navbar {
  background-color: #1e90ff; /* Dodger Blue background */
  color: white;
  text-align: center;
  padding: 10px 0;
  margin-bottom: 20px;
}

.navbar a {
  color: #fff;
  text-decoration: none;
  margin: 0 20px;
  font-weight: bold;
  transition: color 0.3s;
}

.navbar a:hover {
  color: #ff4500; /* Orange-Red on hover */
}

.page-heading h1 {
  text-align: center;
  font-size: 2.5em;
  color: #333; /* Dark gray text color */
  text-transform: uppercase;
  margin: 20px 0;
}


  </style>
 